import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { pworkerHome } from '../settings.mjs';
import { runProgram } from '../sandbox.mjs';
import { createWorkspace } from '../agent/workspace.mjs';
import { randomUUID } from 'node:crypto';

const VAR = /\$([A-Za-z_$][\w$]*)/g;
const ID = /^[A-Za-z_$][\w$]*$/;
const hash = (s) => createHash('sha256').update(s).digest('hex');

export function validateTask(task) {
  if (!task || typeof task !== 'object' || Array.isArray(task)) throw new Error('A task must be an object containing phases.');
  const phases = task.phases ?? task;
  const start = task.start ?? 'begin';
  if (!phases[start]) throw new Error(`Missing initial phase: ${start}.`);
  for (const [name, phase] of Object.entries(phases)) {
    if (['start', 'phases', 'description'].includes(name) && phases === task) continue;
    if (!ID.test(name) || !phase || typeof phase !== 'object') throw new Error(`Invalid phase: ${name}`);
    if (phase.tier != null && (typeof phase.tier !== 'string' || !phase.tier)) throw new Error(`${name}: invalid tier`);
    if (phase.template != null && typeof phase.template !== 'string') throw new Error(`${name}: invalid template`);
    if (phase.batch && !batchTemplate(phase.template ?? '')) throw new Error(`${name}: batching requires exactly one $variable at the end of the template`);
    if (phase.code != null && typeof phase.code !== 'string' && typeof phase.code !== 'function') throw new Error(`${name}: code must be a function or JavaScript string`);
    if (phase.next != null && !phases[phase.next]) throw new Error(`${name}: next phase ${phase.next} does not exist`);
    if (phase.tier == null && phase.batch) throw new Error(`${name}: a model-free phase cannot use batching`);
  }
  return { phases, start };
}

export function batchTemplate(template) {
  const matches = [...String(template).matchAll(VAR)];
  if (matches.length !== 1) return null;
  const m = matches[0];
  return m.index + m[0].length === template.length ? { prefix: template.slice(0, m.index), variable: m[1] } : null;
}

export function renderTemplate(template, state) {
  return String(template).replace(VAR, (_, name) => {
    if (!Object.hasOwn(state, name)) throw new Error(`Variable $${name} is missing from the current request`);
    const value = state[name];
    return typeof value === 'string' ? value : JSON.stringify(value);
  });
}

export async function loadTask(file) {
  const absolute = path.resolve(file);
  if (!absolute.endsWith('.mjs')) throw new Error('The task must be an .mjs file');
  const mod = await import(pathToFileURL(absolute).href);
  const task = mod.default ?? mod.task;
  validateTask(task);
  return task;
}

export async function compileTask(request, { client, home = pworkerHome(), tier = 'good' } = {}) {
  if (!client) throw new Error('A model client is required to compile a request.');
  const dir = path.join(home, 'tasks');
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  const file = path.join(dir, `${hash(request)}.mjs`);
  if (fs.existsSync(file)) return { file, task: await loadTask(file), cached: true };
  const prompt = `Convert the request into a Pworker task. Reply only with a JSON object such as {"start":"begin","phases":{"begin":{"tier":"tiny","template":"... $input","code":"this.end(result)"}}}. Each phase has a tier (a logical tier name or null), a template, and JavaScript code as a string. Code may use this.next("name"), this.end(value), this.variable=value, and result. If currentWorkingDirectory is supplied, phase code may use await this.readFile(path), await this.writeFile(path, text), await this.listFiles(path), await this.moveFile(from, to), await this.makeDirectory(path), and await this.removeFile(path). Paths are confined to that directory. Do not use modules, unrestricted filesystem access, network access, process access, or agentic loops. Use $input for data supplied at execution time. Request:\n${request}`;
  const reply = await client.json({ tier, prompt, cache: 'use', retryCut: true, maxTokens: 4000 });
  if (!reply.ok || !reply.json) throw new Error(`Task compilation failed: ${reply.reason ?? 'invalid JSON'}`);
  const task = reply.json;
  validateTask(task);
  const source = `// Generated by Pworker. Review before using with sensitive input.\nexport default ${JSON.stringify(task, null, 2)};\n`;
  fs.writeFileSync(file, source, { flag: 'wx', mode: 0o600 });
  return { file, task, cached: false };
}

async function runCode(code, result, state, workspace = null) {
  if (code == null) return { state, next: null, ended: false, value: null };
  const source = typeof code === 'function' ? code.toString() : String(code);
  const expression = /^(async\s+)?function\b/.test(source.trim()) || source.includes('=>') ? `(${source}).call(state, result)` : `(async function(result){${source}\n}).call(state, result)`;
  const program = `async function run(api, input) { const state = input.state; const result = input.result; let next = null, ended = false, value = null; Object.defineProperties(state, { next: { configurable: true, value: (name) => { next = name; } }, end: { configurable: true, value: (v) => { ended = true; value = v === undefined ? result : v; } }, readFile: { configurable: true, value: api.readFile }, writeFile: { configurable: true, value: api.writeFile }, listFiles: { configurable: true, value: api.listFiles }, moveFile: { configurable: true, value: api.moveFile }, makeDirectory: { configurable: true, value: api.makeDirectory }, removeFile: { configurable: true, value: api.removeFile } }); await ${expression}; for (const key of ['next','end','readFile','writeFile','listFiles','moveFile','makeDirectory','removeFile']) delete state[key]; return { state, next, ended, value }; }`;
  const api = workspace ? { readFile: ({ path }) => workspace.read(path), writeFile: ({ path, text }) => workspace.write(path, text), listFiles: ({ path: folder, recursive }) => workspace.list(folder ?? '.', { recursive: !!recursive }), moveFile: ({ from, to }) => workspace.move(from, to), makeDirectory: ({ path }) => workspace.makeDirectory(path), removeFile: ({ path }) => workspace.removeFile(path) } : {};
  const response = await runProgram(program, { state, result }, api, { timeMs: 10_000, maxCalls: 100 });
  if (!response.ok) throw new Error(response.message);
  return response.value;
}

export class Pworker {
  constructor({ client, config = {}, home = pworkerHome(), onProgress = null } = {}) {
    if (!client) throw new Error('Pworker requires a model client.');
    this.client = client;
    this.config = config;
    this.home = home;
    this.onProgress = onProgress;
    this.pending = [];
  }

  enqueue(task, input = {}, options = {}) {
    const id = options.id ?? randomUUID();
    if (this.pending.some((item) => item.id === id)) throw new Error(`Duplicate task ID: ${id}`);
    const state = typeof input === 'object' && input !== null && !Array.isArray(input) ? { ...input } : { input };
    const currentWorkingDirectory = options.currentWorkingDirectory ?? state.currentWorkingDirectory ?? null;
    if (currentWorkingDirectory) {
      const absolute = path.resolve(currentWorkingDirectory);
      if (!fs.existsSync(absolute) || !fs.statSync(absolute).isDirectory()) throw new Error(`Working directory does not exist: ${absolute}`);
      state.currentWorkingDirectory = fs.realpathSync(absolute);
    }
    const item = { id, task, state, workspace: state.currentWorkingDirectory ? createWorkspace(state.currentWorkingDirectory) : null, phase: null, done: false, value: undefined, error: null, steps: 0 };
    this.pending.push(item);
    return id;
  }

  async enqueueRequest(requestOrFile, input = {}, options = {}) {
    if (String(requestOrFile).endsWith('.mjs') && !fs.existsSync(requestOrFile)) throw new Error(`Task file does not exist: ${requestOrFile}`);
    const compiled = String(requestOrFile).endsWith('.mjs') && fs.existsSync(requestOrFile) ? { task: await loadTask(requestOrFile), file: path.resolve(requestOrFile), cached: true } : await compileTask(String(requestOrFile), { client: this.client, home: this.home, tier: options.compilerTier ?? 'good' });
    return { id: this.enqueue(compiled.task, input, options), file: compiled.file, cached: compiled.cached };
  }

  async flush() {
    const items = this.pending.splice(0);
    for (const item of items) {
      try { item.definition = validateTask(item.task); item.phase = item.definition.start; this.onProgress?.({ id: item.id, status: 'running', phase: item.phase, steps: item.steps }); }
      catch (e) { item.error = e.message; item.done = true; }
    }
    while (items.some((i) => !i.done)) {
      const active = items.filter((i) => !i.done);
      const groups = new Map();
      for (const item of active) {
        if (++item.steps > 100) { item.done = true; item.error = 'The 100-phase execution limit was exceeded'; continue; }
        this.onProgress?.({ id: item.id, status: 'running', phase: item.phase, steps: item.steps });
        const phase = item.definition.phases[item.phase];
        const pattern = phase.batch && this.config.batching?.[phase.tier]?.enabled ? batchTemplate(phase.template ?? '') : null;
        const key = pattern ? JSON.stringify([item.phase, phase.tier, pattern.prefix, String(phase.code ?? ''), phase.next ?? null]) : item.id;
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key).push(item);
      }
      await Promise.all([...groups.values()].map((group) => this.#advance(group)));
    }
    const results = items.map(({ id, value, state, error, steps }) => ({ id, ok: !error, value, state, error, steps }));
    for (const result of results) this.onProgress?.({ id: result.id, status: result.ok ? 'completed' : 'failed', phase: null, steps: result.steps, result: result.ok ? result : null, error: result.error });
    return results;
  }

  async #advance(group) {
    const first = group[0];
    const phase = first.definition.phases[first.phase];
    const deliver = async (item, result) => {
      let next = phase.next ?? null;
      let ended = false;
      try {
        const outcome = await runCode(phase.code, result, item.state, item.workspace);
        item.state = outcome.state;
        if (outcome.next != null) next = outcome.next;
        ended = outcome.ended;
        if (ended) item.value = outcome.value;
        if (!phase.code && !next) { item.value = result; ended = true; }
        if (ended || !next) { item.done = true; if (!ended) item.value = result; }
        else if (!item.definition.phases[next]) throw new Error(`Phase ${next} does not exist`);
        else { item.phase = next; this.onProgress?.({ id: item.id, status: 'running', phase: next, steps: item.steps }); }
      } catch (e) { item.done = true; item.error = e.message; }
    };
    if (phase.tier == null) { await Promise.all(group.map((item) => deliver(item, undefined))); return; }
    try {
      if (group.length > 1) {
        const { prefix, variable } = batchTemplate(phase.template);
        const requests = group.map((item) => ({ id: item.id, input: item.state[variable] }));
        if (requests.some((x) => x.input === undefined)) throw new Error(`Variable $${variable} is missing`);
        const prompt = `${prefix}\nReturn only a JSON object with a results property that maps each id to its result. Requests:\n${JSON.stringify(requests)}`;
        const r = await this.client.json({ tier: phase.tier, prompt, cache: 'use', retryCut: true });
        if (!r.ok || !r.json?.results || typeof r.json.results !== 'object') throw new Error(`Invalid batch response: ${r.reason ?? 'results is missing'}`);
        for (const item of group) if (!Object.hasOwn(r.json.results, item.id)) throw new Error(`Missing result for ${item.id}`);
        await Promise.all(group.map((item) => deliver(item, r.json.results[item.id])));
      } else {
        const prompt = renderTemplate(phase.template ?? '', first.state);
        const r = await this.client.chat({ tier: phase.tier, prompt, cache: 'use', retryCut: true });
        if (!r.ok) throw new Error(r.reason ?? 'Model request failed');
        await deliver(first, r.text);
      }
    } catch (e) { for (const item of group) { item.done = true; item.error = e.message; } }
  }
}
